### ISSUE TITLE
Gradient descent for cubic regularised problem

### ISSUE THREAD

**Issue by dikam76** [SerVB/tensor-methods#3]
Написть градиентный спуск для задачи min_y  (f'(x_k)^T (y-x_k)+1/2 * (y-x_k)^T f"(x_k) (y-x_k) +L/6 ||y-x_k||^3 )

**Comment by SerVB** [comment]
![image](https://user-images.githubusercontent.com/20105593/81847404-395ac000-955c-11ea-9ea7-30b2f44a184c.png)
